# Generated by Django 4.0.1 on 2022-02-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocall',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocall',
            name='bolnichniy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocall',
            name='request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocall',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
