# Generated by Django 4.0.1 on 2022-02-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videocall_accepted_videocall_bolnichniy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocall',
            name='bolnichniy',
        ),
        migrations.AddField(
            model_name='videocall',
            name='nomer_bolnichnogo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
