# Generated by Django 4.0.1 on 2022-02-08 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_remove_videocall_bolnichniy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocall',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_videocall', to=settings.AUTH_USER_MODEL),
        ),
    ]
