# Generated by Django 4.0.1 on 2022-02-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_videocall_doctor_alter_videocall_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocall',
            name='date_of_call',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='videocall',
            name='url_str',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
