# Generated by Django 4.0.1 on 2022-02-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_videocall_date_of_call_videocall_url_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocall',
            name='date_of_call',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
