# Generated by Django 4.0.1 on 2022-01-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='registration_covid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
