# Generated by Django 4.0.1 on 2022-01-25 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(help_text='Введите номер строения', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(help_text='Введите номер дома', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='room',
            field=models.CharField(help_text='Введите номер квартиры', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Введите адрес', max_length=100, null=True),
        ),
    ]
