# Generated by Django 4.0.1 on 2022-01-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_call_operator_alter_address_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='registration_covid_date',
            field=models.DateTimeField(null=True),
        ),
    ]
