# Generated by Django 4.0.1 on 2022-01-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_complited_call_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_fio',
            field=models.CharField(help_text='Введите ФИО пациента', max_length=1000),
        ),
    ]
