# Generated by Django 4.0.1 on 2022-01-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='patient_fio',
        ),
    ]
