# Generated by Django 4.0.1 on 2022-01-30 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0005_hospital_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='calls.address'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_result', to='calls.call_result'),
        ),
        migrations.AlterField(
            model_name='call',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciyt', to='calls.city'),
        ),
        migrations.AlterField(
            model_name='call',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital', to='calls.hospital'),
        ),
        migrations.AlterField(
            model_name='call',
            name='manipulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manipulation', to='calls.manipulation'),
        ),
        migrations.AlterField(
            model_name='call',
            name='sub_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_subject', to='calls.sub_subject'),
        ),
        migrations.AlterField(
            model_name='call',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='calls.subject'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call', to='calls.call'),
        ),
    ]
