# Generated by Django 4.0.1 on 2022-01-27 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_alter_call_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.call'),
        ),
    ]
