# Generated by Django 4.0.1 on 2022-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_journal_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='active',
        ),
        migrations.AddField(
            model_name='call',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
