# Generated by Django 4.0.1 on 2022-01-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_remove_journal_active_call_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'permissions': (('operator', 'Оператор горячей линии'), ('super_operator', 'Супервайзер горячей линии'), ('hospital_operator', 'Оператор больницы'))},
        ),
    ]
