# Generated by Django 4.0.1 on 2022-02-04 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0010_alter_call_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(help_text='Введите номер дома', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call', to='calls.address'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_number',
            field=models.CharField(help_text='Введите номер с которого звонили', max_length=12),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call', to='calls.call_result'),
        ),
        migrations.AlterField(
            model_name='call',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call', to='calls.city'),
        ),
        migrations.AlterField(
            model_name='call',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call', to='calls.hospital'),
        ),
        migrations.AlterField(
            model_name='call',
            name='manipulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call', to='calls.manipulation'),
        ),
        migrations.AlterField(
            model_name='call',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call', to='calls.subject'),
        ),
    ]
