# Generated by Django 4.0.1 on 2022-02-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_alter_address_number_alter_call_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_subject',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subject', to='calls.subject'),
        ),
    ]
