# Generated by Django 4.0.1 on 2022-02-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_alter_sub_subject_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_subject',
            old_name='genre',
            new_name='subject',
        ),
    ]
