# Generated by Django 4.0.1 on 2022-02-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
